apiVersion: v1
kind: Service
metadata:
  name: poll-automation-service1
spec:
  type: NodePort
  selector:
    app: poll-automation1
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30020 # You can change this to any available port number above 30000
