apiVersion: v1
kind: Service
metadata:
  name: poll-automationpipeline-service
spec:
  type: NodePort
  selector:
    app: poll-automation_pipeline
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30014 # You can change this to any available port number above 30000
